apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "templatephpfpm.fullname" . }}
  labels:
    {{- include "templatephpfpm.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    server {
      listen 0.0.0.0:{{ .Values.service.targetPort }};
      root /app;
      location / {
        index index.html index.php;
      }
      location ~ \.php$ {
        fastcgi_pass {{ include "templatephpfpm.fullname" . }}-phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
