# This Dockerfile uses the latest version of the Bitnami Nginx Docker image
# FROM bitnami/nginx:1.25-debian-11 - vulnerable
# FROM bitnami/nginx:1.25-debian-12 - vulnerable
FROM bitnami/nginx:latest
